/* tslint:disable */
/* eslint-disable */
/**
 * ContactManagerDemo.RestApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserDto
 */
export interface AuthUserDto {
    /**
     * 
     * @type {string}
     * @memberof AuthUserDto
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserDto
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthUserDto
     */
    accessToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthUserDto
     */
    expiresIn?: Date;
    /**
     * 
     * @type {string}
     * @memberof AuthUserDto
     */
    refreshToken?: string | null;
}

/**
 * Check if a given object implements the AuthUserDto interface.
 */
export function instanceOfAuthUserDto(value: object): value is AuthUserDto {
    return true;
}

export function AuthUserDtoFromJSON(json: any): AuthUserDto {
    return AuthUserDtoFromJSONTyped(json, false);
}

export function AuthUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'expiresIn': json['expires_in'] == null ? undefined : (new Date(json['expires_in'])),
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
    };
}

  export function AuthUserDtoToJSON(json: any): AuthUserDto {
      return AuthUserDtoToJSONTyped(json, false);
  }

  export function AuthUserDtoToJSONTyped(value?: AuthUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'] == null ? undefined : ((value['expiresIn']).toISOString()),
        'refresh_token': value['refreshToken'],
    };
}

