/* tslint:disable */
/* eslint-disable */
/**
 * ContactManagerDemo.RestApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityDto
 */
export interface CityDto {
    /**
     * 
     * @type {string}
     * @memberof CityDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CityDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CityDto
     */
    province?: string | null;
}

/**
 * Check if a given object implements the CityDto interface.
 */
export function instanceOfCityDto(value: object): value is CityDto {
    return true;
}

export function CityDtoFromJSON(json: any): CityDto {
    return CityDtoFromJSONTyped(json, false);
}

export function CityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'province': json['province'] == null ? undefined : json['province'],
    };
}

  export function CityDtoToJSON(json: any): CityDto {
      return CityDtoToJSONTyped(json, false);
  }

  export function CityDtoToJSONTyped(value?: CityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'province': value['province'],
    };
}

