/* tslint:disable */
/* eslint-disable */
/**
 * ContactManagerDemo.RestApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    refreshToken?: string | null;
}

/**
 * Check if a given object implements the RefreshTokenRequest interface.
 */
export function instanceOfRefreshTokenRequest(value: object): value is RefreshTokenRequest {
    return true;
}

export function RefreshTokenRequestFromJSON(json: any): RefreshTokenRequest {
    return RefreshTokenRequestFromJSONTyped(json, false);
}

export function RefreshTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

  export function RefreshTokenRequestToJSON(json: any): RefreshTokenRequest {
      return RefreshTokenRequestToJSONTyped(json, false);
  }

  export function RefreshTokenRequestToJSONTyped(value?: RefreshTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'refreshToken': value['refreshToken'],
    };
}

